### ISSUE TITLE
Review 2 - Documentations - Readthedocs documentations should be updated 

### ISSUE THREAD

**Issue by JonnyTran** [BioMeCIS-Lab/OpenOmics#119]
* openOmics version: 0.8.4

### Description
@gawbul 

> Docstrings seem to be available throughout the codebase for all relevant functions, however, I found the documentation on Read the Docs to be lacking in comparison, particularly in providing detail of function parameters that are otherwise available in the docstrings.
> 
> There is no link to the contribution guidelines from the main README, which I feel would be beneficial, however contributing guidelines are available in https://github.com/BioMeCIS-Lab/OpenOmics/blob/master/CONTRIBUTING.rst and on Read the Docs.
> 
> Just being finicky, I personally would prefer a common format for the README and CONTRIBUTING documents etc. Either both in reStructuredText or both in Markdown. There seems to be an outdated README.rst that could probably be replaced with the current README.md?
>

**Comment by JonnyTran** [comment]
Revamped <openomics.readthedocs.io>!

**Comment by gawbul** [comment]
Looks awesome 🤩

**Comment by gawbul** [comment]
I did notice that this section of the docs https://openomics.readthedocs.io/en/latest/usage/getting-started.html#creating-a-multi-omics-dataset was missing the following:

```
from openomics import MultiOmics
```

Otherwise, the following statement fails:

```
luad_data = MultiOmics(cohort_name="LUAD", omics_data=[mRNA, mRNA, lncRNA, som, pro])
```

**Comment by JonnyTran** [comment]
Thanks for pointing this out. I will fix that.
